[project]
name = "search-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Supreme_Engineer98", email = "gmavropouloscoding@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.83.0",
    "openai>=3.18.0",
]

[project.scripts]
search-agent = "search_agent:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
